/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.inventorysystemprj.gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import ec.edu.espe.inventorysystemprj.utils.FilePrj;
import ec.edu.espe.inventorysystemprj.cmd.Customer;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Josselyne Gutiérrez
 */

public class CustomerFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCI = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        btnValidate = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblSurname = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        panelAddress = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblLogo = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuReturn = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        menuSalesNote1 = new javax.swing.JMenu();
        menuAddProducts = new javax.swing.JMenuItem();
        menuShopping = new javax.swing.JMenuItem();
        mnuCustomer = new javax.swing.JMenu();
        menuListCustomer = new javax.swing.JMenuItem();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblTitle.setText("Datos del Cliente");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 33, 209, 40));

        lblCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCI.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCI.setText("CI:");
        getContentPane().add(lblCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 91, 113, 29));

        txtCI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCI.setToolTipText("Digite su cédula de identidad");
        txtCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIActionPerformed(evt);
            }
        });
        txtCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCIKeyPressed(evt);
            }
        });
        getContentPane().add(txtCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 91, 166, -1));

        btnValidate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnValidate.setText("Comprobar CI");
        btnValidate.setToolTipText("Se comprobará la cédula ingresada");
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 91, 141, 29));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Nombre:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 138, 113, 23));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setToolTipText("Escriba su nombre");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 138, 166, -1));

        lblSurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSurname.setText("Apellido:");
        getContentPane().add(lblSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 179, 113, 23));

        txtSurname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSurname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSurname.setToolTipText("Escriba su apellido");
        txtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSurnameActionPerformed(evt);
            }
        });
        txtSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSurnameKeyPressed(evt);
            }
        });
        getContentPane().add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 179, 166, -1));

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhone.setText("Teléfono:");
        getContentPane().add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 220, 113, 23));

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhone.setToolTipText("Digite su número de teléfono");
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 220, 166, -1));

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddress.setText("Dirección:");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 261, 113, 23));

        btnAddCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddCustomer.setText("Añadir Cliente");
        btnAddCustomer.setToolTipText("Se añadirá el cliente");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 179, 38));

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddress.setRows(5);
        txtAddress.setToolTipText("Escriba su dirección");
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddressKeyPressed(evt);
            }
        });
        panelAddress.setViewportView(txtAddress);

        getContentPane().add(panelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 261, 270, 110));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/JMGDistribucionesLogo.png"))); // NOI18N
        lblLogo.setText("jLabel9");
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, 80));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/Background.jpg"))); // NOI18N
        lblBackground.setText("jLabel8");
        lblBackground.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -20, 690, 460));

        jMenu1.setText("Navegación");

        menuReturn.setText("Regresar");
        menuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReturnActionPerformed(evt);
            }
        });
        jMenu1.add(menuReturn);

        menuExit.setText("Salir");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        menuSalesNote1.setText("Nota de Venta");

        menuAddProducts.setText("Añadir Productos");
        menuAddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddProductsActionPerformed(evt);
            }
        });
        menuSalesNote1.add(menuAddProducts);

        menuShopping.setText("Lista de Compras");
        menuShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuShoppingActionPerformed(evt);
            }
        });
        menuSalesNote1.add(menuShopping);

        jMenuBar1.add(menuSalesNote1);

        mnuCustomer.setText("Cliente");

        menuListCustomer.setText("Lista de Clientes");
        menuListCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListCustomerActionPerformed(evt);
            }
        });
        mnuCustomer.add(menuListCustomer);

        jMenuBar1.add(mnuCustomer);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCIActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        FilePrj file = new FilePrj();
        Customer person = new Customer();
        person.setId(Integer.parseInt(txtCI.getText()));
        if (file.searchString("Customer.csv", txtCI.getText())) {

            try {
                Customer customer = new Customer();
                customer = file.searchCustomer("Customer.csv", txtCI.getText());
                txtPhone.setText(String.valueOf(customer.getPhone()));
                txtAddress.setText(String.valueOf(customer.getAddress()));
                String string = customer.getNameAndSurname();
                String[] parts = string.split(" ");
                String name = parts[0];
                String surname = parts[1];
                txtName.setText(String.valueOf(name));
                txtSurname.setText(String.valueOf(surname));
            } catch (IOException ex) {
                Logger.getLogger(CustomerFrame.class.getSimpleName().toString()).log(Level.SEVERE, null, ex);
            }

            txtPhone.setEditable(false);
            txtSurname.setEditable(false);
            txtName.setEditable(false);
            txtCI.setEditable(false);
            txtAddress.setEditable(false);
        } else {
            JOptionPane.showMessageDialog(null, "Persona no encontrada en el sistema");
        }
    }//GEN-LAST:event_btnValidateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        String nameSurname;
        nameSurname = txtName.getText() + " " + txtSurname.getText();
        Customer customer = new Customer();
        customer.setNameAndSurname(nameSurname);
        customer.setId(Integer.parseInt(txtCI.getText()));
        customer.setPhone(Integer.parseInt(txtPhone.getText()));
        customer.setAddress(txtAddress.getText());
        customer.addCostumerToFile();
        this.clean();
        try {
            CustomerTableFrame table = new CustomerTableFrame();
            table.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void txtCIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCIKeyPressed
        char validar = evt.getKeyChar();
        this.verificationJustNumbers(validar, txtCI);
    }//GEN-LAST:event_txtCIKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        char validar = evt.getKeyChar();
        this.verificationJustLetters(validar, txtName);
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtSurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameKeyPressed
        char validar = evt.getKeyChar();
        this.verificationJustLetters(validar, txtSurname);
    }//GEN-LAST:event_txtSurnameKeyPressed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        char validar = evt.getKeyChar();
        this.verificationJustNumbers(validar, txtPhone);
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyPressed
        char validar = evt.getKeyChar();
        this.verificationJustLetters(validar, txtAddress);
    }//GEN-LAST:event_txtAddressKeyPressed

    private void menuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReturnActionPerformed
        SellMenu seller = new SellMenu();
        this.setVisible(false);
        seller.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuReturnActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed
    public void clean() {
        txtCI.setText("");
        txtName.setText("");
        txtSurname.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
    }
    private void menuShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuShoppingActionPerformed

        try {
            this.setVisible(false);
            ListOfShop list = new ListOfShop();
            list.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuShoppingActionPerformed

    private void menuAddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddProductsActionPerformed
        SalesNoteFrame sales;
        try {
            this.setVisible(false);
            sales = new SalesNoteFrame();
            sales.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuAddProductsActionPerformed

    private void menuListCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListCustomerActionPerformed
        CustomerTableFrame customer;
        try {
            customer = new CustomerTableFrame();
            customer.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);

    }//GEN-LAST:event_menuListCustomerActionPerformed

    public void verificationJustLetters(char charValidation, JTextField nameOfTheTextField) {
        if (Character.isDigit(charValidation)) {
            nameOfTheTextField.setBackground(Color.red);
        } else {
            nameOfTheTextField.setBackground(Color.WHITE);

        }
    }

    public void verificationJustNumbers(char charValidation, JTextField nameOfTheTextField) {
        if (Character.isDigit(charValidation)) {
            nameOfTheTextField.setBackground(Color.WHITE);
        } else {
            nameOfTheTextField.setBackground(Color.red);

        }
    }

    public void verificationJustLetters(char charValidation, JTextArea nameOfTheTextArea) {
        if (Character.isDigit(charValidation)) {
            nameOfTheTextArea.setBackground(Color.red);
        } else {
            nameOfTheTextArea.setBackground(Color.WHITE);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnValidate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCI;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem menuAddProducts;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuListCustomer;
    private javax.swing.JMenuItem menuReturn;
    private javax.swing.JMenu menuSalesNote1;
    private javax.swing.JMenuItem menuShopping;
    private javax.swing.JMenu mnuCustomer;
    private javax.swing.JScrollPane panelAddress;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
