/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.inventorysystemprj.gui;

import ec.edu.espe.inventorysystemprj.cmd.ClothingItem;
import ec.edu.espe.inventorysystemprj.cmd.SalesNote;
import ec.edu.espe.inventorysystemprj.utils.FilePrj;
import ec.espe.edu.inventorysystem.controller.Table;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author Josselyne Gutiérrez
 */
public class ListOfShop extends javax.swing.JFrame {

    /**
     * Creates new form ListOfShop
     */
    public ListOfShop() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        ArrayList<ClothingItem> clothes = new ArrayList<ClothingItem>();
        FilePrj file = new FilePrj();
        clothes = file.readClothes("Sales.csv");
        Table table = new Table();
        table.showProducts(clothes, this.tblProducts);
        lblTotal.setText(String.valueOf(this.displayTotal(clothes)));
        SalesNote sales=new SalesNote();
        sales.computeNumberTicket();
        lblTicket.setText(String.valueOf(sales.computeNumberTicket()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTable = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        lblTitleTicket = new javax.swing.JLabel();
        lblTicket = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTittle = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalToPay = new javax.swing.JLabel();
        lblTittleChange = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();
        txtTotalClient = new javax.swing.JTextField();
        btnComputeChange = new javax.swing.JButton();
        btnNewNote = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuReturn = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        menuSalesNote = new javax.swing.JMenu();
        menuAddProducts = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pnlTable.setViewportView(tblProducts);

        getContentPane().add(pnlTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 520, 150));

        lblTitleTicket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitleTicket.setText("Ticket");
        getContentPane().add(lblTitleTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 30));

        lblTicket.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lblTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 70, 30));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Lista de Compras");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 165, 30));

        lblTittle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTittle.setText("Total a pagar:");
        getContentPane().add(lblTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 40));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 60, 40));

        lblTotalToPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotalToPay.setText("Pago del Cliente:");
        getContentPane().add(lblTotalToPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 110, 40));

        lblTittleChange.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTittleChange.setText("Vuelto:");
        getContentPane().add(lblTittleChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 50, 30));

        lblChange.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lblChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 60, 30));

        txtTotalClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalClientActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 90, 30));

        btnComputeChange.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnComputeChange.setText("Calcular Vuelto");
        btnComputeChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeChangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnComputeChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 160, 40));

        btnNewNote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewNote.setText("Nueva Nota de Venta");
        btnNewNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewNoteActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 190, 50));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("Agregar Producto");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 160, 50));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrint.setText("Imprimir");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 100, 50));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/Background.jpg"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 500));

        jMenu1.setText("Navegación");

        menuReturn.setText("Regresar");
        menuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReturnActionPerformed(evt);
            }
        });
        jMenu1.add(menuReturn);

        menuExit.setText("Salir");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        menuSalesNote.setText("Nota de Venta");

        menuAddProducts.setText("Añadir Productos");
        menuAddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddProductsActionPerformed(evt);
            }
        });
        menuSalesNote.add(menuAddProducts);

        jMenuBar1.add(menuSalesNote);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        ArrayList<ClothingItem> clothes = new ArrayList<ClothingItem>();
        SalesNote sales = new SalesNote();
        FilePrj file = new FilePrj();
        try {
            clothes = file.readClothes("Sales.csv");
        } catch (IOException ex) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
        }
        sales.setMoneyTotalToPay(this.displayTotal(clothes));
        sales.acumulateMoney();
        try {
            MessageFormat headerFormat = new MessageFormat("Nota de Venta distruibuidora JMG Distribuciones");
            MessageFormat footerFormat = new MessageFormat("Gracias por preferirnos");
            tblProducts.print(JTable.PrintMode.NORMAL, headerFormat, footerFormat);
        } catch (PrinterException e) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        SalesNoteFrame sales = null;
        try {
            sales = new SalesNoteFrame();
        } catch (IOException ex) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
        }
        sales.setVisible(true);

        this.setVisible(false);

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnComputeChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeChangeActionPerformed
        ArrayList<ClothingItem> clothes = new ArrayList<ClothingItem>();
        SalesNote sales = new SalesNote();
        FilePrj file = new FilePrj();
        try {
            clothes = file.readClothes("Sales.csv");
        } catch (IOException ex) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
        }
        sales.setMoneyTotalToPay(this.displayTotal(clothes));
        sales.setMoneyReceived(Float.parseFloat(txtTotalClient.getText()));
        sales.computeChange();
        lblChange.setText(String.valueOf(sales.getMoneyChange()));
    }//GEN-LAST:event_btnComputeChangeActionPerformed

    private void txtTotalClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalClientActionPerformed

    }//GEN-LAST:event_txtTotalClientActionPerformed

    private void menuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReturnActionPerformed
        SellMenu seller = new SellMenu();
        this.setVisible(false);
        seller.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuReturnActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddProductsActionPerformed
        SalesNoteFrame sales;
        try {
            this.setVisible(false);
            sales = new SalesNoteFrame();
            sales.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuAddProductsActionPerformed

    private void btnNewNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewNoteActionPerformed
        this.setVisible(false);

        try {
            SalesNoteFrame sales = new SalesNoteFrame();
            sales.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
        }

        FilePrj file = new FilePrj();
        try {
            file.deleteFile("Sales.csv");
            file.save("Sales.csv","Quantity;Tipe;Size;Color;Gender;Price");
        } catch (IOException ex) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnNewNoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListOfShop().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public float displayTotal(ArrayList<ClothingItem> clothesSale) {
        SalesNote sales = new SalesNote();
        Iterator<ClothingItem> it = clothesSale.iterator();
        ClothingItem clothes = new ClothingItem(0, 0);
        float total = 0;
        while (it.hasNext()) {
            clothes = it.next();
            total = total + sales.computeTotal(clothes.getPrice(), clothes.getQuantity());
        }
        return total;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnComputeChange;
    private javax.swing.JButton btnNewNote;
    private javax.swing.JButton btnPrint;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblTicket;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleTicket;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblTittleChange;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalToPay;
    private javax.swing.JMenuItem menuAddProducts;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuReturn;
    private javax.swing.JMenu menuSalesNote;
    private javax.swing.JScrollPane pnlTable;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtTotalClient;
    // End of variables declaration//GEN-END:variables
}
