/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.inventorysystemprj.gui;

import ec.edu.espe.inventorysystemprj.cmd.ProfitsReport;
import ec.edu.espe.inventorysystemprj.utils.FilePrj;
import ec.espe.edu.inventorysystem.controller.Validation;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.JTextField;

/**
 *
 * @author Josselyne Gutiérrez
 */
public class ProfitsReportFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfitsReport
     */
    public ProfitsReportFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfitsReport = new javax.swing.JLabel();
        lblInvestments = new javax.swing.JLabel();
        lblSalesMoney = new javax.swing.JLabel();
        btnComputeProfits = new javax.swing.JButton();
        txtInvestment = new javax.swing.JTextField();
        lblSalesMoneyFile = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuNavegation = new javax.swing.JMenu();
        menuReturn = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        mnuCustomer = new javax.swing.JMenu();
        menuAddCustomer = new javax.swing.JMenuItem();
        menuSalesNote = new javax.swing.JMenu();
        menuAddProducts = new javax.swing.JMenuItem();
        menuShopping = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfitsReport.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblProfitsReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfitsReport.setText("Reporte de ganancias");
        getContentPane().add(lblProfitsReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 42, 220, 61));

        lblInvestments.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblInvestments.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInvestments.setText("Inversiones");
        lblInvestments.setToolTipText("");
        getContentPane().add(lblInvestments, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 121, 90, 43));

        lblSalesMoney.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblSalesMoney.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSalesMoney.setText("Dinero de ventas");
        getContentPane().add(lblSalesMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, 43));

        btnComputeProfits.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnComputeProfits.setText("Calcular Ganancias");
        btnComputeProfits.setToolTipText("Se calculará las ganancias");
        btnComputeProfits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeProfitsActionPerformed(evt);
            }
        });
        getContentPane().add(btnComputeProfits, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 263, -1, 67));

        txtInvestment.setToolTipText("Digite las inversiones efectuadas");
        txtInvestment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvestmentActionPerformed(evt);
            }
        });
        txtInvestment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInvestmentKeyPressed(evt);
            }
        });
        getContentPane().add(txtInvestment, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 122, 166, 44));

        lblSalesMoneyFile.setBackground(new java.awt.Color(255, 255, 255));
        lblSalesMoneyFile.setText(" ");
        lblSalesMoneyFile.setToolTipText("Digite el dinero obtenido por ventas");
        lblSalesMoneyFile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblSalesMoneyFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 179, 166, 43));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/JMGDistribucionesLogo.png"))); // NOI18N
        lblLogo.setText("jLabel9");
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, 80));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/Background.jpg"))); // NOI18N
        lblBackground.setText("jLabel1");
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -140, 620, 550));

        mnuNavegation.setText("Navegación");

        menuReturn.setText("Regresar");
        menuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReturnActionPerformed(evt);
            }
        });
        mnuNavegation.add(menuReturn);

        menuExit.setText("Salir");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        mnuNavegation.add(menuExit);

        jMenuBar1.add(mnuNavegation);

        mnuCustomer.setText("Cliente");

        menuAddCustomer.setText("Añadir Cliente");
        menuAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddCustomerActionPerformed(evt);
            }
        });
        mnuCustomer.add(menuAddCustomer);

        jMenuBar1.add(mnuCustomer);

        menuSalesNote.setText("Nota de Venta");

        menuAddProducts.setText("Añadir Productos");
        menuAddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddProductsActionPerformed(evt);
            }
        });
        menuSalesNote.add(menuAddProducts);

        menuShopping.setText("Lista de Compras");
        menuShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuShoppingActionPerformed(evt);
            }
        });
        menuSalesNote.add(menuShopping);

        jMenuBar1.add(menuSalesNote);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComputeProfitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeProfitsActionPerformed

        if (Validation.isAnyEmpty(txtInvestment)) {
            JOptionPane.showMessageDialog(null, "El campo de inversiones está vacío", "ERROR", WARNING_MESSAGE);
        } else {
            ProfitsReport profits = new ProfitsReport();
            profits.setInvestment(Float.parseFloat(txtInvestment.getText()));
            String fileName = "SalesMoney.csv";
            FilePrj file = new FilePrj();
            file.exists(fileName);
            float sales;
            float investment;
            {
                try {
                    sales = file.readSalesMoney(fileName);
                    profits.setTotalOfSalesMoney(sales);
                } catch (IOException ex) {
                }
            }
            lblSalesMoneyFile.setText(String.valueOf(profits.computeProfits()));
        }
    }//GEN-LAST:event_btnComputeProfitsActionPerformed

    private void txtInvestmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvestmentActionPerformed

    }//GEN-LAST:event_txtInvestmentActionPerformed

    private void txtInvestmentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInvestmentKeyPressed
        char validar = evt.getKeyChar();
        Validation.verificationJustNumbers(validar, txtInvestment);
    }//GEN-LAST:event_txtInvestmentKeyPressed

    private void menuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReturnActionPerformed
        SellMenu seller = new SellMenu();
        this.setVisible(false);
        seller.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuReturnActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddCustomerActionPerformed
        CustomerFrame customer = new CustomerFrame();
        customer.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuAddCustomerActionPerformed

    private void menuShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuShoppingActionPerformed

        try {
            this.setVisible(false);
            ListOfShop list = new ListOfShop();
            list.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuShoppingActionPerformed

    private void menuAddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddProductsActionPerformed
        SalesNoteFrame sales;
        try {
            this.setVisible(false);
            sales = new SalesNoteFrame();
            sales.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuAddProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfitsReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfitsReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfitsReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfitsReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfitsReportFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComputeProfits;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblInvestments;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblProfitsReport;
    private javax.swing.JLabel lblSalesMoney;
    private javax.swing.JLabel lblSalesMoneyFile;
    private javax.swing.JMenuItem menuAddCustomer;
    private javax.swing.JMenuItem menuAddProducts;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuReturn;
    private javax.swing.JMenu menuSalesNote;
    private javax.swing.JMenuItem menuShopping;
    private javax.swing.JMenu mnuCustomer;
    private javax.swing.JMenu mnuNavegation;
    private javax.swing.JTextField txtInvestment;
    // End of variables declaration//GEN-END:variables
}
