/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.inventorysystemprj.gui;

import ec.edu.espe.inventorysystemprj.cmd.ClothingItem;
import ec.edu.espe.inventorysystemprj.utils.FilePrj;
import ec.espe.edu.inventorysystem.controller.Table;
import ec.espe.edu.inventorysystem.controller.Validation;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.JTable;

/**
 *
 * @author @TopCoders
 */
public class SalesNoteFrame extends javax.swing.JFrame {

    ArrayList<ClothingItem> clothesSale =new ArrayList<ClothingItem>();
    
    /**
     * Creates new form SalesNoteFrame
     */
    public SalesNoteFrame() throws IOException {
        initComponents();
         this.setLocationRelativeTo(null);
        Table table = new Table();
        table.updateClothes(cmbChooseClothes);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogo = new javax.swing.JLabel();
        cmbChooseClothes = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        pnlProducts = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnChoose = new javax.swing.JButton();
        btnSale = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuReturn = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        mnuCustomer = new javax.swing.JMenu();
        menuAddCustomer = new javax.swing.JMenuItem();
        menuSalesNote = new javax.swing.JMenu();
        menuAddProducts = new javax.swing.JMenuItem();
        menuShopping = new javax.swing.JMenuItem();
        mnuProfits = new javax.swing.JMenu();
        mnuProfitsReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/JMGDistribucionesLogo.png"))); // NOI18N
        lbLogo.setText("jLabel9");
        getContentPane().add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 80));

        cmbChooseClothes.setToolTipText("Escoja una opción ");
        cmbChooseClothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChooseClothesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbChooseClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 145, 36));

        txtQuantity.setToolTipText("Escriba la cantidad que desea añadir a la nota de venta");
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 70, -1));

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducts.setToolTipText("Tabla de productos disponibles");
        pnlProducts.setViewportView(tblProducts);

        getContentPane().add(pnlProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 510, 190));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Cantidad a comprar:");
        jLabel1.setToolTipText("Cantidad a comprar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 140, 20));

        btnChoose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChoose.setText("Seleccionar");
        btnChoose.setToolTipText("Seleccionar el producto escogido");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });
        getContentPane().add(btnChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 120, 50));

        btnSale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSale.setText("Nota de Venta");
        btnSale.setToolTipText("Genera una nota de venta");
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });
        getContentPane().add(btnSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 160, 50));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Artículos disponibles para vender");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 22, 306, 63));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/Background.jpg"))); // NOI18N
        lblBackground.setText("jLabel3");
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -50, 670, 550));

        jMenu1.setText("Navegación");

        menuReturn.setText("Regresar");
        menuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReturnActionPerformed(evt);
            }
        });
        jMenu1.add(menuReturn);

        menuExit.setText("Salir");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        mnuCustomer.setText("Cliente");

        menuAddCustomer.setText("Añadir Cliente");
        menuAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddCustomerActionPerformed(evt);
            }
        });
        mnuCustomer.add(menuAddCustomer);

        jMenuBar1.add(mnuCustomer);

        menuSalesNote.setText("Nota de Venta");

        menuAddProducts.setText("Añadir Productos");
        menuAddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddProductsActionPerformed(evt);
            }
        });
        menuSalesNote.add(menuAddProducts);

        menuShopping.setText("Lista de Compras");
        menuShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuShoppingActionPerformed(evt);
            }
        });
        menuSalesNote.add(menuShopping);

        jMenuBar1.add(menuSalesNote);

        mnuProfits.setText("Ganancias");

        mnuProfitsReport.setText("Reporte");
        mnuProfitsReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProfitsReportActionPerformed(evt);
            }
        });
        mnuProfits.add(mnuProfitsReport);

        jMenuBar1.add(mnuProfits);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbChooseClothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChooseClothesActionPerformed
        try {
            this.showClothes(cmbChooseClothes.getSelectedItem().toString());
        } catch (IOException ex) {
            Logger.getLogger(SalesNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbChooseClothesActionPerformed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        if (Validation.isAnyEmpty(txtQuantity)) {
            JOptionPane.showMessageDialog(null, "El campo de cantidad está vacío", "ERROR", WARNING_MESSAGE);
        } else {

            Table tableMethod = new Table();
            FilePrj file = new FilePrj();
            ClothingItem clothing = new ClothingItem(0, 0);
            clothing = tableMethod.getInfoTable(tblProducts);
            try {
                file.changeQuantity("StoreHouse.csv", clothing, -Integer.parseInt(txtQuantity.getText().toString()));
            } catch (IOException ex) {
                Logger.getLogger(SalesNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            clothing.setQuantity(Integer.parseInt(txtQuantity.getText().toString()));
            clothesSale.add(clothing);
            txtQuantity.setText("");

            JOptionPane.showMessageDialog(null, "Se ha agregado el producto correctamente", "Advertencia", WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnChooseActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
   
        FilePrj file = new FilePrj();
        Iterator<ClothingItem> it = clothesSale.iterator();
        ClothingItem clothes = new ClothingItem(0, 0);
        file.exists("Sales.csv");
        int i = 0;
        if(!it.hasNext())
        {
            JOptionPane.showMessageDialog(null,"No se ha escogido ninguna prenda","ERROR", WARNING_MESSAGE);
            
        }
        while (it.hasNext()) {
            clothes = it.next();
            file.save("Sales.csv", file.convertsToString(clothes));

            try {
                ListOfShop list = new ListOfShop();
                list.setVisible(true);
                dispose();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null,"No se ha escogido ninguna prenda","ERROR", WARNING_MESSAGE);
            }
        }
          
    }//GEN-LAST:event_btnSaleActionPerformed

    private void menuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReturnActionPerformed
        SellMenu seller = new SellMenu();
        this.setVisible(false);
        seller.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuReturnActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddCustomerActionPerformed
        CustomerFrame customer = new CustomerFrame();
        customer.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuAddCustomerActionPerformed

    private void menuAddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddProductsActionPerformed
        SalesNoteFrame sales;
        try {
            this.setVisible(false);
            sales = new SalesNoteFrame();
            sales.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuAddProductsActionPerformed

    private void menuShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuShoppingActionPerformed

        try {
            this.setVisible(false);
            ListOfShop list = new ListOfShop();
            list.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuShoppingActionPerformed

    private void mnuProfitsReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProfitsReportActionPerformed
        ProfitsReportFrame profits =new ProfitsReportFrame();
        this.setVisible(false);
        profits.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuProfitsReportActionPerformed

    public void showClothes(String type) throws IOException
    {
        FilePrj file =new FilePrj();
        ArrayList<ClothingItem> clothing=new ArrayList<>();
        String fileName="StoreHouse.csv";
        clothing=file.searchClothes(fileName,type);
       
        Table table=new Table();
        table.showProducts(clothing, tblProducts);
    }
    
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesNoteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesNoteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesNoteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesNoteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new SalesNoteFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(SalesNoteFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnSale;
    private javax.swing.JComboBox<String> cmbChooseClothes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem menuAddCustomer;
    private javax.swing.JMenuItem menuAddProducts;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuReturn;
    private javax.swing.JMenu menuSalesNote;
    private javax.swing.JMenuItem menuShopping;
    private javax.swing.JMenu mnuCustomer;
    private javax.swing.JMenu mnuProfits;
    private javax.swing.JMenuItem mnuProfitsReport;
    private javax.swing.JScrollPane pnlProducts;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
