/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.inventorysystemprj.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Josselyne Gutiérrez
 */
public class SellMenu extends javax.swing.JFrame {

    /**
     * Creates new form SellMenu
     */
    public SellMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblStore = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuNavegation = new javax.swing.JMenu();
        menuReturn = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        mnuCustomer = new javax.swing.JMenu();
        menuAddCustomer = new javax.swing.JMenuItem();
        menuSalesNote = new javax.swing.JMenu();
        menuAddProducts = new javax.swing.JMenuItem();
        menuShopping = new javax.swing.JMenuItem();
        mnuProfits = new javax.swing.JMenu();
        mnuProfitsReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Bienvenido");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 170, 70));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/JMGDistribucionesLogo.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 150, 150));

        lblStore.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblStore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStore.setText("Vendedores");
        getContentPane().add(lblStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 320, 70));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/Background.jpg"))); // NOI18N
        lblBackground.setText("jLabel1");
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 620, 410));

        mnuNavegation.setText("Navegación");

        menuReturn.setText("Regresar");
        menuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReturnActionPerformed(evt);
            }
        });
        mnuNavegation.add(menuReturn);

        menuExit.setText("Salir");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        mnuNavegation.add(menuExit);

        jMenuBar1.add(mnuNavegation);

        mnuCustomer.setText("Cliente");

        menuAddCustomer.setText("Añadir Cliente");
        menuAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddCustomerActionPerformed(evt);
            }
        });
        mnuCustomer.add(menuAddCustomer);

        jMenuBar1.add(mnuCustomer);

        menuSalesNote.setText("Nota de Venta");

        menuAddProducts.setText("Añadir Productos");
        menuAddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddProductsActionPerformed(evt);
            }
        });
        menuSalesNote.add(menuAddProducts);

        menuShopping.setText("Lista de Compras");
        menuShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuShoppingActionPerformed(evt);
            }
        });
        menuSalesNote.add(menuShopping);

        jMenuBar1.add(menuSalesNote);

        mnuProfits.setText("Ganancias");

        mnuProfitsReport.setText("Reporte");
        mnuProfitsReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProfitsReportActionPerformed(evt);
            }
        });
        mnuProfits.add(mnuProfitsReport);

        jMenuBar1.add(mnuProfits);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReturnActionPerformed
        LoginFrame login=new LoginFrame();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuReturnActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddCustomerActionPerformed
        CustomerFrame customer = new CustomerFrame();
        customer.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuAddCustomerActionPerformed

    private void menuAddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddProductsActionPerformed
        SalesNoteFrame sales;
        try {
            this.setVisible(false);
            sales = new SalesNoteFrame();
            sales.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(ListOfShop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuAddProductsActionPerformed

    private void menuShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuShoppingActionPerformed

        try {
            this.setVisible(false);
            ListOfShop list = new ListOfShop();
            list.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuShoppingActionPerformed

    private void mnuProfitsReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProfitsReportActionPerformed
        ProfitsReportFrame profits =new ProfitsReportFrame();
        this.setVisible(false);
        profits.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuProfitsReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblStore;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem menuAddCustomer;
    private javax.swing.JMenuItem menuAddProducts;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuReturn;
    private javax.swing.JMenu menuSalesNote;
    private javax.swing.JMenuItem menuShopping;
    private javax.swing.JMenu mnuCustomer;
    private javax.swing.JMenu mnuNavegation;
    private javax.swing.JMenu mnuProfits;
    private javax.swing.JMenuItem mnuProfitsReport;
    // End of variables declaration//GEN-END:variables
}
