/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.inventorysystemprj.gui;

import ec.edu.espe.inventorysystemprj.cmd.ClothingItem;
import ec.edu.espe.inventorysystemprj.cmd.StoreHouse;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;


/**
 *
 * @author Fernanda Galárraga
 */
public class StoreHouseFrame extends javax.swing.JFrame {

    /**
     * Creates new form StoreHouseFrame
     */
    public StoreHouseFrame() {
        initComponents();
         this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        btnAdd1 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        lblTittle = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        pnlProduct = new javax.swing.JPanel();
        rBtnBelt = new javax.swing.JRadioButton();
        rBtnSkullcap = new javax.swing.JRadioButton();
        rBtnPants = new javax.swing.JRadioButton();
        rBtnHat = new javax.swing.JRadioButton();
        rBtnShirt = new javax.swing.JRadioButton();
        rBtnJacket = new javax.swing.JRadioButton();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblSize = new javax.swing.JLabel();
        pnlSize = new javax.swing.JPanel();
        rBtnSmall = new javax.swing.JRadioButton();
        rBtnMedium = new javax.swing.JRadioButton();
        rBtnLarge = new javax.swing.JRadioButton();
        rBtnExtraLarge = new javax.swing.JRadioButton();
        lblColor = new javax.swing.JLabel();
        pnlColor = new javax.swing.JPanel();
        rBtnBlack = new javax.swing.JRadioButton();
        rBtnRed = new javax.swing.JRadioButton();
        rBtnBrown = new javax.swing.JRadioButton();
        lblGender = new javax.swing.JLabel();
        pnlGender = new javax.swing.JPanel();
        rBtnFemale = new javax.swing.JRadioButton();
        rBtnMale = new javax.swing.JRadioButton();
        lblLogo = new javax.swing.JLabel();
        btnDeleteClothe = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuProducts = new javax.swing.JMenuItem();
        menuReturn = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        btnAdd1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd1.setText("AÑADIR");
        btnAdd1.setToolTipText("Se añadirá el producto");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTittle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTittle.setText("       ALMACÉN");
        getContentPane().add(lblTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 168, 36));

        lblProduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProduct.setText("SELECCIONE UN PRODUCTO");
        getContentPane().add(lblProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 31));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("AÑADIR");
        btnAdd.setToolTipText("Se añadirá el producto");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 124, 45));

        pnlProduct.setToolTipText("Escoja el producto que desee");

        rBtnBelt.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnBelt);
        rBtnBelt.setText("Cinturón");
        rBtnBelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnBeltActionPerformed(evt);
            }
        });

        rBtnSkullcap.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnSkullcap);
        rBtnSkullcap.setText("Gorro");
        rBtnSkullcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnSkullcapActionPerformed(evt);
            }
        });

        rBtnPants.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnPants);
        rBtnPants.setText("Pantalón");

        rBtnHat.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnHat);
        rBtnHat.setText("Sombrero");

        rBtnShirt.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnShirt);
        rBtnShirt.setText("Camisa");

        rBtnJacket.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rBtnJacket);
        rBtnJacket.setText("Chaqueta");

        javax.swing.GroupLayout pnlProductLayout = new javax.swing.GroupLayout(pnlProduct);
        pnlProduct.setLayout(pnlProductLayout);
        pnlProductLayout.setHorizontalGroup(
            pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBtnJacket, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnShirt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnHat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnPants, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnSkullcap, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnBelt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProductLayout.setVerticalGroup(
            pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(rBtnBelt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnSkullcap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnPants)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnHat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnShirt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnJacket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQuantity.setText("CANTIDAD");
        getContentPane().add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        txtQuantity.setToolTipText("Digite la cantidad que desee");
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantityKeyTyped(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 60, -1));

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrice.setText("PRECIO");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        txtPrice.setText(" ");
        txtPrice.setToolTipText("Digite el precio del producto");
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 60, -1));

        lblSize.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSize.setText("TALLA");
        getContentPane().add(lblSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        pnlSize.setToolTipText("Escoja la talla que necesite");

        rBtnSmall.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rBtnSmall);
        rBtnSmall.setText("Small");

        rBtnMedium.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rBtnMedium);
        rBtnMedium.setText("Medium");

        rBtnLarge.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rBtnLarge);
        rBtnLarge.setText("Large");
        rBtnLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnLargeActionPerformed(evt);
            }
        });

        rBtnExtraLarge.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rBtnExtraLarge);
        rBtnExtraLarge.setText("Extra-Large");

        javax.swing.GroupLayout pnlSizeLayout = new javax.swing.GroupLayout(pnlSize);
        pnlSize.setLayout(pnlSizeLayout);
        pnlSizeLayout.setHorizontalGroup(
            pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rBtnSmall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rBtnMedium, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(rBtnLarge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rBtnExtraLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSizeLayout.setVerticalGroup(
            pnlSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rBtnSmall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnExtraLarge)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, -1));

        lblColor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblColor.setText("COLOR");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 30));

        pnlColor.setToolTipText("Escoja el color que desee");

        rBtnBlack.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rBtnBlack);
        rBtnBlack.setText("Negro");
        rBtnBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnBlackActionPerformed(evt);
            }
        });

        rBtnRed.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rBtnRed);
        rBtnRed.setText("Rojo");

        rBtnBrown.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rBtnBrown);
        rBtnBrown.setText("Café");
        rBtnBrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnBrownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlColorLayout = new javax.swing.GroupLayout(pnlColor);
        pnlColor.setLayout(pnlColorLayout);
        pnlColorLayout.setHorizontalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColorLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBtnBrown, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnRed, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlColorLayout.setVerticalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rBtnBlack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnRed, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnBrown)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGender.setText("GÉNERO");
        getContentPane().add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        pnlGender.setToolTipText("Escoja el genero ");

        rBtnFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(rBtnFemale);
        rBtnFemale.setText("Mujer");

        rBtnMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(rBtnMale);
        rBtnMale.setText("Hombre");

        javax.swing.GroupLayout pnlGenderLayout = new javax.swing.GroupLayout(pnlGender);
        pnlGender.setLayout(pnlGenderLayout);
        pnlGenderLayout.setHorizontalGroup(
            pnlGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBtnMale, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGenderLayout.setVerticalGroup(
            pnlGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rBtnMale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnFemale)
                .addContainerGap())
        );

        getContentPane().add(pnlGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 80, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/JMGDistribucionesLogo.png"))); // NOI18N
        lblLogo.setText("jLabel9");
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 160, 80));

        btnDeleteClothe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/inventorysystemprj/images/Background.jpg"))); // NOI18N
        btnDeleteClothe.setText("j");
        getContentPane().add(btnDeleteClothe, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -160, 800, 610));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Eliminar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        jMenu1.setText("Navegación");

        menuProducts.setText("Lista de Productos");
        menuProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductsActionPerformed(evt);
            }
        });
        jMenu1.add(menuProducts);

        menuReturn.setText("Regresar");
        menuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReturnActionPerformed(evt);
            }
        });
        jMenu1.add(menuReturn);

        menuExit.setText("Salir");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rBtnLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnLargeActionPerformed
        
    }//GEN-LAST:event_rBtnLargeActionPerformed

    private void rBtnBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnBlackActionPerformed
        
    }//GEN-LAST:event_rBtnBlackActionPerformed

    private void rBtnBeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnBeltActionPerformed
        
    }//GEN-LAST:event_rBtnBeltActionPerformed

    private void rBtnSkullcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnSkullcapActionPerformed
        
    }//GEN-LAST:event_rBtnSkullcapActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
       
        
       
        
    }//GEN-LAST:event_txtQuantityActionPerformed

    
      private void agregationClothes(){
       ArrayList<String> staticTypes=new ArrayList<String>();
       staticTypes.add("Cinturon");
       staticTypes.add("Gorro");
       staticTypes.add("Pantalon");
       staticTypes.add("Sombrero");
       staticTypes.add("Camisa");
       staticTypes.add("Chaqueta");
       staticTypes.add("Zapatos");
       
       ClothingItem clothesObj;
       ArrayList<ClothingItem> clothes=new ArrayList<>();
        
       float getPrice=Float.parseFloat(txtPrice.getText());
       int getColor=0;
       int getSize=0;
       int getGender=0;
       int getQuantity=Integer.parseInt(txtQuantity.getText());
       
       
       staticTypes.add(rBtnBelt.getText());
       staticTypes.add(rBtnSkullcap.getText());
       staticTypes.add(rBtnPants.getText());
       staticTypes.add(rBtnHat.getText());
       staticTypes.add(rBtnShirt.getText());
       staticTypes.add(rBtnJacket.getText());
       
        if(rBtnSmall.isSelected()==true) getSize=1;
        if(rBtnMedium.isSelected()==true) getSize=2;
        if(rBtnLarge.isSelected()==true) getSize=3;
        if(rBtnExtraLarge.isSelected()==true) getSize=4;
        
        if(rBtnBlack.isSelected()==true) getColor=1;
        if(rBtnRed.isSelected()==true) getColor=2;
        if(rBtnBrown.isSelected()==true) getColor=3;
        
        if(rBtnMale.isSelected()==true) getGender=1;
        if(rBtnFemale.isSelected()==true) getGender=2;
        
       StoreHouse storeHouse = new StoreHouse();
       
      
        
        if(rBtnBelt.isSelected()==true){
         clothesObj = new ClothingItem(staticTypes.get(0).toString(),getPrice,getSize,getColor,getGender,getQuantity);
         clothesObj.setType(staticTypes.get(0).toString());
         clothes.add(clothesObj);       
        }         
        if(rBtnSkullcap.isSelected()==true){
         clothesObj = new ClothingItem(staticTypes.get(1).toString(),getPrice,getSize,getColor,getGender,getQuantity);
         clothesObj.setType(staticTypes.get(1).toString());
         clothes.add(clothesObj);   
        }
        if(rBtnPants.isSelected()==true){
         clothesObj = new ClothingItem(staticTypes.get(2).toString(),getPrice,getSize,getColor,getGender,getQuantity);
         clothesObj.setType(staticTypes.get(2).toString());
         clothes.add(clothesObj);
        }
        if(rBtnHat.isSelected()==true){
         clothesObj = new ClothingItem(staticTypes.get(3).toString(),getPrice,getSize,getColor,getGender,getQuantity);
         clothesObj.setType(staticTypes.get(3).toString());
         clothes.add(clothesObj);  
        }
        if(rBtnShirt.isSelected()==true){
         clothesObj = new ClothingItem(staticTypes.get(4).toString(),getPrice,getSize,getColor,getGender,getQuantity);
         clothesObj.setType(staticTypes.get(4).toString());
         clothes.add(clothesObj);  
        }
        if(rBtnJacket.isSelected()==true){
         clothesObj = new ClothingItem(staticTypes.get(5).toString(),getPrice,getSize,getColor,getGender,getQuantity);
         clothesObj.setType(staticTypes.get(5).toString());
         clothes.add(clothesObj);   
        }
        
        Iterator<ClothingItem> itrClothes = clothes.iterator();
        while(itrClothes.hasNext()){
	ClothingItem clothesS = itrClothes.next();
                
                storeHouse.addClothesToFile(clothesS);   
            
        }
    }
    
      
     public void clean()
     {
         txtPrice.setText("");
         txtQuantity.setText("");
    
     }
    
    
    
    
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       agregationClothes();
       clean();
    }//GEN-LAST:event_btnAddActionPerformed

    private void rBtnBrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnBrownActionPerformed
        
    }//GEN-LAST:event_rBtnBrownActionPerformed

    private void txtQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyTyped
        char c =evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtQuantityKeyTyped

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
       char ca =evt.getKeyChar();
        if(ca<'0'||ca>'9') evt.consume();
    }//GEN-LAST:event_txtPriceKeyTyped

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
    
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReturnActionPerformed
       StoreMenu store=new StoreMenu();
       this.setVisible(false);
       store.setVisible(true);
       dispose();
    }//GEN-LAST:event_menuReturnActionPerformed

    private void menuProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductsActionPerformed
        ListProduct list;
        try {
            list = new ListProduct();
            list.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(StoreHouseFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_menuProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String [] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreHouseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreHouseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreHouseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreHouseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreHouseFrame().setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JLabel btnDeleteClothe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuProducts;
    private javax.swing.JMenuItem menuReturn;
    private javax.swing.JPanel pnlColor;
    private javax.swing.JPanel pnlGender;
    private javax.swing.JPanel pnlProduct;
    private javax.swing.JPanel pnlSize;
    private javax.swing.JRadioButton rBtnBelt;
    private javax.swing.JRadioButton rBtnBlack;
    private javax.swing.JRadioButton rBtnBrown;
    private javax.swing.JRadioButton rBtnExtraLarge;
    private javax.swing.JRadioButton rBtnFemale;
    private javax.swing.JRadioButton rBtnHat;
    private javax.swing.JRadioButton rBtnJacket;
    private javax.swing.JRadioButton rBtnLarge;
    private javax.swing.JRadioButton rBtnMale;
    private javax.swing.JRadioButton rBtnMedium;
    private javax.swing.JRadioButton rBtnPants;
    private javax.swing.JRadioButton rBtnRed;
    private javax.swing.JRadioButton rBtnShirt;
    private javax.swing.JRadioButton rBtnSkullcap;
    private javax.swing.JRadioButton rBtnSmall;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
